# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Heather B-Log
# email: 
description: > # this means to ignore newlines until "baseurl:"
  These are the words that I've had to say in the past whenever.
  Go ahead and consume them.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://heatherbooker.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: hboo_codes
github_username:  heatherbooker

# Build settings
markdown: kramdown
# theme: leonids
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock


owner:
  name: Heather Booker
  avatar: heatherlearns.svg
  job: "Good morning."
  bio: "These are the words that I've had to say in the past whenever."
  bio2: "Go ahead and consume them."
  email:
  disqus-shortname:
  twitter: "hboo_codes"
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: heatherbooker
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username