#!/bin/bash
# This script creates a new post or draft in jekyll with pre-filled front matter.
# Run `./new <some title for your post>` to generate a post.
# Run `./new -d <title AFTER -d flag>` for a draft.

ISDRAFT=false
while getopts "d" opt; do
    case $opt in
        d)
            ISDRAFT=true
            ;;
    esac
done
shift $((OPTIND-1))

TITLE=""
for word in $@
do
    # `sed` to replace all chars except alphanum or - with empty string.
    alphanumericword=$(echo $word | sed "s/[^A-Za-z0-9-]//g")
    # ${alphanumericword,,} <-- This converts the word to lowercase.
    TITLE+="-${alphanumericword,,}"
done

FILEDIR="_posts"
FILENAME="$FILEDIR/$(date +%Y-%m-%d)$TITLE.md"

# Insert frontmatter in post
echo "---" > $FILENAME

echo "layout: post" >> $FILENAME

if [ $# -gt 0 ]
  then
    echo "title: \"$@\"" >> $FILENAME
fi

echo "tags: DON'T FORGET!!" >> $FILENAME

if $ISDRAFT; then
    echo "draft: true" >> $FILENAME
fi

echo "---" >> $FILENAME

# Write the post
if command -v nvim >/dev/null 2>&1
then
    nvim $FILENAME
else
    vi $FILENAME
fi
