#!/bin/bash
# This script creates a new post or draft in jekyll with pre-filled front matter.
# Run `./new <some title for your post>` to generate a post.
# Run `./new -d <title AFTER -d flag>` for a draft.

FILEDIR="_posts/"
ISDRAFT=false

while getopts "d" opt; do
    case $opt in
        d)
            ISDRAFT=true
            ;;
    esac
done
shift $((OPTIND-1))

TITLE=""
for word in $@
do
    # `sed` will replace all chars except alphanum with empty string.
    alphanumericword=$(echo $word | sed "s/[^A-Za-z0-9]//g")
    # ${alphanumericword,,} <-- This converts the word to lowercase.
    TITLE+="-${alphanumericword,,}"
done

FILENAME="$FILEDIR$(date +%Y-%m-%d)$TITLE.md"

echo "---" > $FILENAME
echo "layout: post" >> $FILENAME

if [ $# -gt 0 ]
  then
    echo "title: \"$@\"" >> $FILENAME
fi

echo "tags: DON'T FORGET!!" >> $FILENAME

if $ISDRAFT; then
    echo "draft: true" >> $FILENAME
fi

echo "---" >> $FILENAME

vim $FILENAME
