#!/bin/bash
# This script creates a new thought in jekyll with pre-filled front matter.
# Run `./thought` to generate a thought.

set -e

FILEDIR="thoughts"
FILENAME="$FILEDIR/$(date +%F-%H-%M-%S).md"

echo "---" > $FILENAME
echo "date: $(date '+%F %T')" >> $FILENAME
echo "---" >> $FILENAME

if command -v nvim >/dev/null 2>&1
then
    nvim $FILENAME
else
    vi $FILENAME
fi

# Useful post-post stuff
git add $FILENAME
git commit -m "Think a thought"
echo "You thinked a thought! Run 'git push' to tell the world! Or just to get it off your chest."
